### ISSUE TITLE
Frontier nonce does not increase when tx failed?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#492]
This is different behavior compared to Ethereum

**Comment by AsceticBear** [comment]
https://github.com/paritytech/frontier/issues/301

**Comment by AsceticBear** [comment]
I have reinvestigated this issue again and I would like to expand more on it:

Here we divide the transaction failure into two cases:
1. The tx fails before it enters the EVM executor.
2. The tx enters the EVM executor but fails during execution.

It is so important to note that [inc_nonce](https://github.com/darwinia-network/darwinia-common/blob/master/frame/evm/src/runner/stack.rs#L450) occurs inside the EVM executor, which is crucial for analyzing this problem.

For the first case, before https://github.com/paritytech/frontier/pull/299 , the tx sometimes dies before it enters the EVM executor, so `inc_nonce` cannot be called. At this point, I send a tx, but the tx fails and the nonce is not added by 1. That the reason why this issue was created.

For the second case, the tx fails inside the EVM executor. In this case, since [inc_nonce](https://github.com/rust-blockchain/evm/blob/master/src/executor/stack/mod.rs#L221) occurs before [enter_substrate](https://github.com/rust-blockchain/evm/blob/master/src/executor/stack/mod.rs#L483), even if the tx fails, the nonce value will not roll back when [exit_substrate](https://github.com/rust-blockchain/evm/blob/master/src/executor/stack/mod.rs#L497) is eventually executed.

In a word, I think this issue has been fixed after https://github.com/paritytech/frontier/pull/299 merged.

@HackFisher Please take some time to read this anylysis. I think it's time to close this issue.

**Comment by AsceticBear** [comment]
@HackFisher Please take some time to read this analysis. I think it's time to close this issue.

**Comment by HackFisher** [comment]
Actually, there are three cases in dvm/frontier:

1. `validate_unsigned`, to validate the ethereum tx in mempool, if validation fails, it will not be even enclosed in blocks.
2. `transact` dispatch call, and if fail before `execute`, the extrinsic will fail before EVM executor, as you said, nonce will not be added by 1, but this should merely happen since most check should have been run in step 1 `validate_unsigned`.

The nonce will increase even if it failed in this step(beginning of extrinsic):


https://github.com/paritytech/substrate/blob/3efe87daba09be18b3596e075c3733fe47bafdd5/frame/system/src/extensions/check_nonce.rs#L84


https://github.com/darwinia-network/darwinia-common/blob/a00d1031acb941161d79d9d06611a3b27539b60f/frame/dvm/src/lib.rs#L217


3. `T::Runner::call`, inside EVM executor, if the nonce is increased before entering `substate`(Note: `substate` not `substrate`), then it is consistent with Ethereum.

So if the tx is included in block(2 and 3), nonce should always increase by 1 as my understanding, otherwise, it might be bug.

If the original case is no more reproducible, we can close this issue.

**Comment by HackFisher** [comment]
Related #564

**Comment by HackFisher** [comment]
My mistake, `CheckNonce ` seems to work only for SignedExtension, not `ValidateUnsigned `

https://github.com/paritytech/substrate/blob/3efe87daba09be18b3596e075c3733fe47bafdd5/frame/system/src/extensions/check_nonce.rs#L84

So it will not work for ethereum tx, we still have issues with in above step 2.

Any way, I still think we should deal with that in DVM/Frontier.

**Comment by AsceticBear** [comment]
Everything is working fine. Close it.
