### ISSUE TITLE
Extensible Address Format integrating with DVM

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#493]
Check whether we could improve and support MultiAddress:

https://github.com/paritytech/substrate/pull/7380

https://github.com/darwinia-network/darwinia/wiki/Darwinia-Address-Format-Overview

**Comment by HackFisher** [comment]
https://github.com/paritytech/substrate/pull/7380/files#diff-e49bba681e4bc724d3b659e04a55ba286d1a5e1bc93c75eced44a6062b7385baR302

**Comment by HackFisher** [comment]
@AsceticBear Please help answer wether we need to handle this.

**Comment by AsceticBear** [comment]
Sorry for the delay. As there are few docs talk about this feature now, I am trying to figure out how the multiaddress feature integrates with other substrate-based projects.
 
The only project I found uses the MultiAddress feature is moonbeam. They integrate it with Polkadot js SDK and show Eth Address as their only basic account model. 

1. Docs: https://docs.moonbeam.network/integrations/wallets/polkadotjs/
2. Test Demos: https://github.com/AsceticBear/substrate-node-template/tree/use-ethereum-as-primary-account

Due to the fact that darwinia uses the sr25519 as the basic account model and a conversion protocol between substrate account to evm account, I do not think this feature should be handled.
