### ISSUE TITLE
Offchain Worker Get Header from Substrate off-chain db

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#53]
Currently all data come from EtherScan.

**Comment by HackFisher** [comment]
For darwinia-offchain-tools, the relay worker is splitted into two processes, relayer and fetcher, and follow the producer and consumer model.

For fetcher, it could provide an additional option to directly sync canonical  block header datas to substrate off-chain db using rpc call, then the substrate offchain worker might able to directly read the header data synced by fetcher.

**Comment by yanganto** [comment]
It is good to get ethereum block from multiple source, and the issue was opened.
https://github.com/darwinia-network/darwinia/issues/371

The etherum block will be validated in the offchain worker, the block relayed is always safe.
The only concern is the etherum api stop, our bridge will stop.

Once the relay automatically switch the vetween ethereum sources, and one of the ethereum sources is provided by us, the relay service will be robust and almost the same as read from local db.

I will set the last step on getting header from local db, because this is the most affort.

**Comment by HackFisher** [comment]
Substrate wasm only have interfaces to substrate offchain db, suppose that is what "local db" means, if not, the other local db stuffs should be request using http request with the help of companion service.
