### ISSUE TITLE
Make `darwinia/substrate` a Submodule?

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#8]
Easy to manage/upgrade deps. Avoid too many files changes.

**Comment by HackFisher** [comment]
Let's use cargo for less mental attention, and cargo is more capable for managing different dependency versions

**Comment by clearloop** [comment]
It's quite clean if we use substrate as a sub module, we can write out deps like:

```
[dependencies]
substrate-xxxx = { path = "path/to/substrate-submodule" }
```

instead of 

```
[dependencies]
substrate-xxxx = { git = "long url + commit hash" }
```

and

> Easy to manage/upgrade deps. Avoid too many files changes.


## write it in the workspace

This will make our binary larger than now, because `cargo build` will build all members in the workspace.

## write like a [git-submodule][0]

We can just ref pallets instead of building all, if we decide to make it a sub-module, this might be the solution.


[0]: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by AurevoirXavier** [comment]
> It's quite clean if we use substrate as a sub module, we can write our deps like:
> 
> ```
> [dependencies]
> substrate-xxxx = { path = "path/to/substrate-submodule" }
> ```

Yep, using the path also can help people to learn substrate's framework. And konw how these component work together.

**Comment by HackFisher** [comment]
Imagine this for example, we could have two runtimes, mainet and crab.
mainet runtime could depend on darwinia-common on version v0.6.0
crab runtime could depend on darwinia-common on version v0.5.0

submodule way does not match this requirement well.

**Comment by AurevoirXavier** [comment]
Currently we've 2 branch **master** (lastest update) and **darwinia-master** (stable version). Just like the **crab** and **darwinia**.

**Comment by HackFisher** [comment]
> Currently we've 2 branch **master** (lastest update) and **darwinia-master** (stable version). Just like the **crab** and **darwinia**.

Different branch works well for dependency, but it' kind of disturbing to introduce multi submodules.

And submodule need extra git submodule init and update operations.
