### ISSUE TITLE
Modifiable and generalize of MIN_RELAYERS_NUMBER in relayer fee market

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-common#861]
https://github.com/darwinia-network/darwinia-common/pull/779#discussion_r728054346

Currently, MIN_RELAYERS_NUMBER must not be modified to other values different with 3. If we going to that in future, we need to make changes to support it being modifiable by generalization of MIN_RELAYERS_NUMBER.

**Comment by HackFisher** [comment]
I changes this issue to high priority due to the easier local testnet setup requirements from @xiaoch05 
https://github.com/darwinia-network/darwinia-common/blob/master/frame/fee-market/README.md#detailed-steps-in-implementation

Eash allocation in step 5 is the same for each relayer in the selected set.

**Comment by HackFisher** [comment]
Document need to be updated:
```
Order Relayer for index (t - start)/interval can claim 60% from the reward price, if lowest price P1 is L, and message relayer can claim 80% * (1 - 60%) from L， confirm relayer can claim 20% * (1 - 60%) from L, leaving part from user fee will go to treasury
```
